# Generated by Django 5.0.6 on 2026-06-18 10:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehousing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Ідентифікатор')),
                ('license_plate', models.CharField(max_length=10, verbose_name='Номерний знак')),
                ('driver_name', models.CharField(max_length=100, verbose_name="Ім'я водія")),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Поточна локація')),
                ('max_capacity_tons', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Вантажопідйомність')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Доступний'), ('ON_WAY', 'В дорозі'), ('LOADING', 'Завантаження'), ('DELIVERING', 'Доставляється'), ('UNLOADING', 'Розвантаження')], default='AVAILABLE', max_length=15, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Місце доставки')),
                ('status', models.CharField(choices=[('CREATED', 'Створено'), ('ASSIGNED', 'Назначено'), ('IN_PROGRESS', 'В процесі'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Відмінено')], default='CREATED', max_length=15, verbose_name='Статус')),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Відстань (км)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час завершення')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehousing.grainbatch', verbose_name='Партія')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousing.warehouse', verbose_name='Місце збору')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.truck', verbose_name='Транспортний засіб')),
            ],
        ),
    ]
