# Generated by Django 5.0.6 on 2026-06-18 10:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Координати меж поля')),
                ('area_hectares', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Площа (га)')),
                ('crop_status', models.CharField(choices=[('PLANNED', 'Заплановано'), ('SOWN', 'Посіяно'), ('GERMINATED', 'Сходи (Проростання)'), ('GROWING', 'Вегетація (Росте)'), ('FLOWERING', 'Цвітіння'), ('RIPENING', 'Дозрівання'), ('READY', 'Готово до збору'), ('HARVESTED', 'Зібрано'), ('FAILED', 'Втрачено (Загинуло)')], default='PLANNED', max_length=15, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_analytics.company', verbose_name='Компанія')),
            ],
        ),
        migrations.CreateModel(
            name='FieldMetricHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('weather_raw_data', models.JSONField(verbose_name='Сира відповідь')),
                ('ndvi_index', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Індекс вегетації')),
                ('soil_moisture', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Вологість')),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Температура')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_analytics.field', verbose_name='Поле')),
            ],
        ),
    ]
