# Generated by Django 5.0.6 on 2026-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='area_hectares',
            field=models.FloatField(blank=True, null=True, verbose_name='Площа (га)'),
        ),
    ]
