# Generated by Django 5.0.6 on 2026-06-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_analytics', '0002_alter_field_area_hectares'),
        ('users', '0003_company_alter_user_company'),
        ('warehousing', '0002_alter_warehouse_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Компанія'),
        ),
        migrations.RemoveField(
            model_name='fieldmetrichistory',
            name='field',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='FieldMetricHistory',
        ),
    ]
