# Generated by Django 5.0.6 on 2026-06-18 10:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo_analytics', '0001_initial'),
        ('smart_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_class', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Клас зерна')),
                ('moisture', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Вологість')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_planning.cropculture', verbose_name='Тип культури')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_analytics.field', verbose_name='Поле')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координати')),
                ('capacity_tons', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Вместимість')),
                ('current_balance_tons', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Поточний баланс')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_analytics.company', verbose_name='Компанія')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('INCOMING', 'Надходження'), ('OUTGOING', 'Списання/відвантаження'), ('RESERVED', 'Бронювання під логістику')], default='INCOMING', max_length=15, verbose_name='Тип операції')),
                ('weight_tons', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Вага (тонна)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('operator_id', models.UUIDField(verbose_name='ID оператора')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousing.grainbatch', verbose_name='Бакет')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousing.warehouse', verbose_name='Склад')),
            ],
        ),
    ]
