# Generated by Django 5.0.6 on 2026-06-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_alter_user_company'),
        ('warehousing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Компанія'),
        ),
        migrations.AlterField(
            model_name='warehousejournalentry',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousing.grainbatch', verbose_name='Партія'),
        ),
    ]
