# Generated by Django 5.0.6 on 2026-06-18 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCulture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optimal_moisture_min', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Мінімальна вологість')),
                ('optimal_moisture_max', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Максимальна вологість')),
                ('optimal_temp_min', models.FloatField(validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Мінімальна температура')),
                ('optimal_temp_max', models.FloatField(validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Максимальна температура')),
                ('average_yield_per_ha', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Середня врожайність')),
                ('base_market_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Базова ціна на ринку')),
            ],
        ),
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Коефіцієнт впевненості')),
                ('expected_yield', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Очікувана врожайність')),
                ('estimated_profit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Очікувана чиста вартість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCycleMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Рік')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Місяць')),
                ('total_precipitation', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Загальний опад')),
                ('avg_temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Середня температура')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cropculture',
            constraint=models.CheckConstraint(check=models.Q(('optimal_temp_max__gte', models.F('optimal_temp_min'))), name='max_temp_gte_min_temp'),
        ),
        migrations.AddConstraint(
            model_name='cropculture',
            constraint=models.CheckConstraint(check=models.Q(('optimal_moisture_max__gte', models.F('optimal_moisture_min'))), name='max_moisture_gte_min_moisture'),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_analytics.field', verbose_name='Поле'),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='suggested_crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_planning.cropculture', verbose_name='Рекомендована культура'),
        ),
    ]
