# Generated by Django 5.0.6 on 2026-06-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_planning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherCycleMatrix',
        ),
    ]
